### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by seasonlei** [blocklords/seascape-js#2]
![5](https://user-images.githubusercontent.com/60209171/178694220-a9241eb7-e782-457b-b808-9113fe1ea4a6.png)
I added this to my deployment contract js file
But the following error was reported
So, please help me figure out how to get him through
The following are reported errors
![2](https://user-images.githubusercontent.com/60209171/178694796-70f40a6f-0c44-451c-bbb1-85e07699abe1.png)
![3](https://user-images.githubusercontent.com/60209171/178694800-5d1999c3-62d4-4b58-beb0-dc0df3305587.png)
![4](https://user-images.githubusercontent.com/60209171/178694823-6aafe5f2-8054-4b40-9464-39b13bb76090.png)
Thanks!

**Comment by ahmetson** [comment]
@seasonlei check that the Alicloud credentials don't have a whitespace in the .env
